// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  App.FormController = (function() {
    function FormController() {
      this.reset = __bind(this.reset, this);
      this.formParams = __bind(this.formParams, this);
      this.runAlgorithm = __bind(this.runAlgorithm, this);      this.form = $('#params-form');
      this.form.bind("submit", this.runAlgorithm);
      $("#reset-button").bind('click', this.reset);
      this.cache = {};
      this.defaultTasks = [
        {
          id: 1,
          total: 10,
          arrival: 0
        }, {
          id: 2,
          total: 10,
          arrival: 0
        }, {
          id: 3,
          total: 10,
          arrival: 0
        }
      ];
    }

    FormController.prototype.runAlgorithm = function(event) {
      event.preventDefault();
      this.reset();
      this.cache = {};
      return this.scheduleRun();
    };

    FormController.prototype.formParams = function() {
      var _base, _ref;

      return (_ref = (_base = this.cache)['params']) != null ? _ref : _base['params'] = this.form.serializeArray().reduce(function(previousValue, currentValue, index, array) {
        previousValue[currentValue.name] = currentValue.value;
        return previousValue;
      }, {});
    };

    FormController.prototype.scheduleRun = function() {
      return this.selectedAlgorithm().schedule(this.schedulerOptions(), (new App.ProcessAnimator).enequeProcess);
    };

    FormController.prototype.selectedAlgorithm = function() {
      var _base, _ref;

      return (_ref = (_base = this.cache)['algoConstant']) != null ? _ref : _base['algoConstant'] = new App.Schedulers["" + (this.formParams()['algorithm'])];
    };

    FormController.prototype.schedulerOptions = function() {
      return {
        tasks: this.tasks(),
        config: this.schedulerConfig()
      };
    };

    FormController.prototype.schedulerConfig = function() {
      return {
        timeSlice: this.formParams()['timeSlice']
      };
    };

    FormController.prototype.tasks = function() {
      var _this = this;

      return this.defaultTasks.map(function(val) {
        return {
          id: val.id,
          total: parseInt(_this.formParams()["total-t" + val.id]),
          priority: parseInt(_this.formParams()["priority-t" + val.id]),
          arrival: parseInt(_this.formParams()["arrival-t" + val.id])
        };
      });
    };

    FormController.prototype.reset = function() {
      return $('.process').width(0);
    };

    return FormController;

  })();

  $(function() {
    return window.formController = new App.FormController;
  });

}).call(this);
