// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  App.FormController = (function() {
    function FormController() {
      this.retrieveParams = __bind(this.retrieveParams, this);      this.form = $('#params-form');
      this.form.bind("submit", this.retrieveParams);
    }

    FormController.prototype.retrieveParams = function(event) {
      event.preventDefault();
      return this.params = this.form.serializeArray();
    };

    return FormController;

  })();

  $(function() {
    return new App.FormController;
  });

}).call(this);
