// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  App.ProcessAnimator = (function() {
    function ProcessAnimator() {
      this.process = __bind(this.process, this);
      this.animate = __bind(this.animate, this);      this.processCache = {};
      this.defaultUnitSize = 5;
    }

    ProcessAnimator.prototype.animate = function(process, units) {
      return this.process(process.id).style.width = "" + (this.process(process.id).offsetWidth + units * this.defaultUnitSize) + "px";
    };

    ProcessAnimator.prototype.process = function(processId) {
      var _base, _name, _ref;

      return (_ref = (_base = this.processCache)[_name = "" + processId]) != null ? _ref : _base[_name] = document.getElementById("process-" + processId);
    };

    return ProcessAnimator;

  })();

}).call(this);
