// Generated by CoffeeScript 1.6.2
App.ProcessAnimator = (function() {
  ProcessAnimator.defaultUnitSize = 5;

  function ProcessAnimator() {
    this.processCache = {};
  }

  ProcessAnimator.prototype.animate = function(processId, units) {
    return this.process(processId).style.width = "" + (this.process(processId).offsetWidth + units * 5) + "px";
  };

  ProcessAnimator.prototype.process = function(processId) {
    var _base, _name, _ref;

    return (_ref = (_base = this.processCache)[_name = "" + processId]) != null ? _ref : _base[_name] = document.getElementById("process-" + processId);
  };

  return ProcessAnimator;

})();
